import "../globals.css";
import Topheader from "@/components/Topheader";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Quicksand, Fraunces } from "next/font/google";

const quicksand = Quicksand({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-quicksand",
  });
  const fraunces = Fraunces({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-fraunces",
  });
  export const metadata = {
    title: "Bookstore",
    description: "Generated by create next app",
  };

export default function MainLayout({ children }) {
    return (
      <html lang="en" className={`${quicksand.variable} ${fraunces.variable}`}>
        <body className="flex min-h-screen bg-primary flex-col relative">
          <Topheader />
         <Navbar />
          {children}
       
        </body>
      </html>
    );
  }